import Foundation
import SwiftUI

struct PulseVisualThemeEnvironmentKey: EnvironmentKey {
    /// Uninjected trees must show the free theme, never a paid skin.
    static let defaultValue = PulseVisualThemeAccessPolicy.freeTheme
}

extension EnvironmentValues {
    var pulseVisualTheme: PulseVisualTheme {
        get { self[PulseVisualThemeEnvironmentKey.self] }
        set { self[PulseVisualThemeEnvironmentKey.self] = newValue }
    }
}

struct PulseThemePalette {
    let canvas: Color
    let canvasDeep: Color
    let surface: Color
    let ink: Color
    let muted: Color
    let divider: Color
    let accent: Color
    let accentForeground: Color
    let accentSoft: Color
}

enum PulseDesign {
    // Brand colors resolve from Assets.xcassets generated by build_brand_assets.py.
    // Destructive controls follow the platform semantic color, not a brand token.
    static let background = Color("PulseBackground")
    static let surface = Color("PulseSurface")
    static let quietCanvas = Color("PulseQuietCanvas")
    static let quietDivider = Color("PulseQuietDivider")
    static let quietGreen = Color("PulseQuietGreen")
    static let quietGreenSoft = Color("PulseQuietGreenSoft")
    static let quietInk = Color("PulseQuietInk")
    static let quietMuted = Color("PulseQuietMuted")
    static let quietOnGreen = Color("PulseQuietOnGreen")
    static let quietSurface = Color("PulseQuietSurface")
    static let grass = Color("PulseGrass")
    static let grassForeground = Color("PulseGrassForeground")
    static let action = Color("PulseAction")
    static let actionForeground = Color("PulseActionForeground")
    static let ink = Color("PulseInk")
    static let moonAccent = Color("PulseMoonAccent")
    static let moonAccentForeground = Color("PulseMoonAccentForeground")
    static let moonAccentSoft = Color("PulseMoonAccentSoft")
    static let moonCanvas = Color("PulseMoonCanvas")
    static let moonCanvasDeep = Color("PulseMoonCanvasDeep")
    static let moonCoral = Color("PulseMoonCoral")
    static let moonDivider = Color("PulseMoonDivider")
    static let moonDiscInk = Color("PulseMoonDiscInk")
    static let moonInk = Color("PulseMoonInk")
    static let moonMuted = Color("PulseMoonMuted")
    static let moonSurface = Color("PulseMoonSurface")
    static let prismAccent = Color("PulsePrismAccent")
    static let prismAccentForeground = Color("PulsePrismAccentForeground")
    static let prismAccentSoft = Color("PulsePrismAccentSoft")
    static let prismCanvas = Color("PulsePrismCanvas")
    static let prismCanvasDeep = Color("PulsePrismCanvasDeep")
    static let prismCoral = Color("PulsePrismCoral")
    static let prismDivider = Color("PulsePrismDivider")
    static let prismInk = Color("PulsePrismInk")
    static let prismMuted = Color("PulsePrismMuted")
    static let prismSurface = Color("PulsePrismSurface")
    static let secondary = Color("PulseSecondary")
    static let separator = Color("PulseSeparator")
    static let field = Color("PulseField")
    static let editorialAccent = Color("PulseEditorialAccent")
    static let editorialCanvas = Color("PulseEditorialCanvas")
    static let editorialSurface = Color("PulseEditorialSurface")
    static let editorialInk = Color("PulseEditorialInk")
    static let editorialMuted = Color("PulseEditorialMuted")
    static let editorialDivider = Color("PulseEditorialDivider")
    static let editorialOnAccent = Color("PulseEditorialOnAccent")
    static let editorialAccentSoft = Color("PulseEditorialAccentSoft")
    static let sunlitCanvas = Color("PulseSunlitCanvas")
    static let sunlitCanvasDeep = Color("PulseSunlitCanvasDeep")
    static let sunlitSurface = Color("PulseSunlitSurface")
    static let sunlitInk = Color("PulseSunlitInk")
    static let sunlitMuted = Color("PulseSunlitMuted")
    static let sunlitDivider = Color("PulseSunlitDivider")
    static let sunlitAccent = Color("PulseSunlitAccent")
    static let sunlitWeekday = Color("PulseSunlitWeekday")
    static let sunlitAccentSoft = Color("PulseSunlitAccentSoft")
    static let sunlitChrome = Color("PulseSunlitChrome")
    static let sunlitChromeForeground = Color("PulseSunlitChromeForeground")
    static let sunlitOnAccent = Color("PulseSunlitOnAccent")
    static let immersionCanvas = Color("PulseImmersionCanvas")
    static let immersionCanvasDeep = Color("PulseImmersionCanvasDeep")
    static let immersionSurface = Color("PulseImmersionSurface")
    static let immersionInk = Color("PulseImmersionInk")
    static let immersionMuted = Color("PulseImmersionMuted")
    static let immersionDivider = Color("PulseImmersionDivider")
    static let immersionAccent = Color("PulseImmersionAccent")
    static let immersionAccentForeground = Color("PulseImmersionAccentForeground")
    static let immersionAccentSoft = Color("PulseImmersionAccentSoft")
    static let shadow = Color("PulseShadow")
    static let tint = Color("AccentColor")
    static let systemDestructive = Color(uiColor: .systemRed)
    static let spacing4: CGFloat = 4
    static let spacing8: CGFloat = 8
    static let spacing12: CGFloat = 12
    static let spacing16: CGFloat = 16
    static let spacing20: CGFloat = 20
    static let spacing24: CGFloat = 24
    static let spacing32: CGFloat = 32

    static let horizontalPadding: CGFloat = spacing20
    static let screenMaxWidth: CGFloat = 680
    static let editorialContentMaxWidth: CGFloat = 720
    static let historyMaxWidth: CGFloat = 760
    static let regularWidthContentMaxWidth: CGFloat = 1_080
    static let regularWidthColumnGap: CGFloat = spacing32 + spacing16
    static let regularWidthVerticalPadding: CGFloat = spacing32
    static let minimumHitTarget: CGFloat = 44
    static let detailActionHitSize: CGFloat = minimumHitTarget + spacing4
    static let compactDetailDetentFraction = 0.32
    static let journalDetailDetentFraction = 0.52

    static let topBarHeight: CGFloat = 58
    static let brandMarkSize: CGFloat = 28
    static let brandMarkCornerRadius: CGFloat = 8

    static let sunlitPrintCornerRadius: CGFloat = 6
    static let quietStalkHeight: CGFloat = 216
    static let quietStalkNodeDiameter: CGFloat = 11
    static let quietStalkLineWidth: CGFloat = 4
    static let quietStalkMaxNodes = 7
    static let quietBladeMaxHeight: CGFloat = 26
    static let quietBladeWidth: CGFloat = 7
    static let sunlitExposureNumberSize: CGFloat = 148
    static let sunlitExposureNumberTracking: CGFloat = -4
    static let editorialNavigationStripCornerRadius: CGFloat = 10
    static let editorialNavigationSegmentCornerRadius: CGFloat = 7
    static let editorialNavigationStripHeight: CGFloat = 52
    static let editorialNavigationStripPadding: CGFloat = spacing4
    static let editorialNavigationSelectedFillOpacity = 0.08
    static let editorialNavigationOuterVerticalPadding: CGFloat = spacing12
    static let checkInInnerHalo: CGFloat = 18
    static let checkInOuterHalo: CGFloat = 36
    static let editorialCheckInVerticalPadding: CGFloat = checkInOuterHalo + spacing16

    static let primaryNavigationMaxWidth: CGFloat = 440
    static let primaryNavigationHeight: CGFloat = 72
    static let primaryNavigationCornerRadius: CGFloat = 24
    static let primaryNavigationItemCornerRadius: CGFloat = 18
    static let primaryNavigationGap: CGFloat = spacing8
    static let primaryNavigationPadding: CGFloat = spacing8
    static let primaryNavigationGlyph: CGFloat = 30
    static let primaryNavigationHorizontalInset: CGFloat = spacing16
    static let accessibilityNavigationMinimumHeight: CGFloat = 88
    static let accessibilityNavigationGlyphMaximum: CGFloat = 48
    static let ledgerNavigationHeight: CGFloat = 76
    static let ledgerNavigationGlyph: CGFloat = minimumHitTarget

    static let calendarDayVisualSize: CGFloat = 34
    static let calendarDayHitSize: CGFloat = minimumHitTarget
    static let calendarAccessoryGlyphSize: CGFloat = 8
    static let onboardingBrandMarkSize: CGFloat = 68
    static let mediaCardMaxWidth: CGFloat = 420
    static let mediaPreviewFailureMinimumHeight: CGFloat = 220
    static let mediaCornerRadius: CGFloat = 24
    static let mediaCompanionOffsetX: CGFloat = spacing16
    static let mediaCompanionOffsetY: CGFloat = spacing8
    static let mediaCompanionThumbnailSize: CGFloat = 28
    static let thinLineWidth: CGFloat = 1
    static let emphasisLineWidth: CGFloat = 2
    static let calendarBeforeHabitOpacity = 0.62
    static let disabledControlOpacity = 0.38

    static let storeBrandMarkSize: CGFloat = 72
    static let storePreviewWidth: CGFloat = 248
    static let storePreviewHeight: CGFloat = 148
    static let activityStoreSurfaceCornerRadius: CGFloat = 22
    static let activityStoreExpandedMinimumHeight: CGFloat = 72
    static let activityStoreCompactHeight: CGFloat = 40
    static let activityStoreMinimalDiameter: CGFloat = 40
    static let activityStoreLockScreenMinimumHeight: CGFloat = 88
    static let storeCapabilityIconSize: CGFloat = 36
    static let storeCapabilityMinimumHeight: CGFloat = 88
    static let storePurchaseButtonMinimumHeight: CGFloat = 56
    static let widgetMediumAspectRatio: CGFloat = 338.0 / 158.0
    static let widgetPreviewPairAspectRatio: CGFloat = 338.0 / (
        (338.0 - spacing8) / (1 + widgetMediumAspectRatio)
    )
    static let widgetGalleryCardCornerRadius: CGFloat = 28
    static let widgetPreviewCornerRadius: CGFloat = 20
    static let storeHeroCornerRadius: CGFloat = 32
    static let storeCapabilityCornerRadius: CGFloat = 22
    static let themePreviewHeight: CGFloat = 116
    static let themePreviewCornerRadius: CGFloat = 18
    static let themePreviewUnselectedBorderOpacity = 0.28
    static let journalDraftMinimumHeight: CGFloat = 76
    static let journalHistoryExcerptLineLimit = 4
    static let historyModePickerHeight: CGFloat = minimumHitTarget
    static let historyModePickerCornerRadius: CGFloat = 12
    static let historyModePickerItemCornerRadius: CGFloat = 9
    static let historyModePickerInset: CGFloat = spacing4
    static let historyModePickerSurfaceOpacity = 0.82
    static let editorialLineHeight: CGFloat = 3
    static let editorialLineInitialWidth: CGFloat = 36
    static let editorialKickerTracking: CGFloat = 0.06
    static let journalHistorySurfaceOpacity = 0.72

    static let savingAnimationDuration = 0.18
    static let savingIndicatorDelay = 0.25
    static let checkInLongPressDuration = 0.45
    static let checkInPressMovementTolerance: CGFloat = 28
    static let imprintContractionDuration = 0.16
    static let imprintFormationDuration = 0.24
    static let imprintSettleDuration = 0.22
    static let imprintReducedMotionFadeDuration = 0.18
    static let completionRippleDuration = 0.46
    static let completionSettleDamping = 0.72
    static let completionSecondaryDelay = 0.14
    static let completionSecondaryDuration = 0.28
    static let primaryNavigationSelectionDuration = 0.24
    static let mediaDetailDismissDelay = 0.24
    static let primaryContentTransitionDuration = 0.18
    static let editorialAccentExpansionDuration = 0.55
    static let primaryContentTransitionOffset: CGFloat = spacing8
    static let monthTransitionDuration = 0.2
    static let completionRippleStartScale: CGFloat = 0.92
    static let completionRippleEndScale: CGFloat = 1.55
    static let imprintGlyphSize: CGFloat = 24
    static let imprintGlyphLineWidth: CGFloat = 2
    static let imprintDotScale: CGFloat = 0.08
    static let imprintOvershootScale: CGFloat = 1.12
    static let idleAuraCollapsedScale: CGFloat = 0.96
    static let idleAuraExpandedScale: CGFloat = 1.06

    static let imprintCompletionDuration =
        imprintContractionDuration + imprintFormationDuration + imprintSettleDuration

    static func palette(for theme: PulseVisualTheme) -> PulseThemePalette {
        switch theme {
        case .editorialJournal:
            PulseThemePalette(
                canvas: editorialCanvas,
                canvasDeep: editorialCanvas,
                surface: editorialSurface,
                ink: editorialInk,
                muted: editorialMuted,
                divider: editorialDivider,
                accent: editorialAccent,
                accentForeground: editorialOnAccent,
                accentSoft: editorialAccentSoft
            )
        case .sunlitDay:
            PulseThemePalette(
                canvas: sunlitCanvas,
                canvasDeep: sunlitCanvasDeep,
                surface: sunlitSurface,
                ink: sunlitInk,
                muted: sunlitMuted,
                divider: sunlitDivider,
                accent: sunlitAccent,
                accentForeground: sunlitOnAccent,
                accentSoft: sunlitAccentSoft
            )
        case .quietField:
            PulseThemePalette(
                canvas: quietCanvas,
                canvasDeep: quietCanvas,
                surface: quietSurface,
                ink: quietInk,
                muted: quietMuted,
                divider: quietDivider,
                accent: quietGreen,
                accentForeground: quietOnGreen,
                accentSoft: quietGreenSoft
            )
        case .prismLedger:
            PulseThemePalette(
                canvas: prismCanvas,
                canvasDeep: prismCanvasDeep,
                surface: prismSurface,
                ink: prismInk,
                muted: prismMuted,
                divider: prismDivider,
                accent: prismAccent,
                accentForeground: prismAccentForeground,
                accentSoft: prismAccentSoft
            )
        case .immersion:
            PulseThemePalette(
                canvas: immersionCanvas,
                canvasDeep: immersionCanvasDeep,
                surface: immersionSurface,
                ink: immersionInk,
                muted: immersionMuted,
                divider: immersionDivider,
                accent: immersionAccent,
                accentForeground: immersionAccentForeground,
                accentSoft: immersionAccentSoft
            )
        }
    }

    static func appAccent(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).accent
    }

    static func appSuccess(for theme: PulseVisualTheme) -> Color {
        switch theme {
        case .editorialJournal:
            editorialAccent
        case .sunlitDay:
            sunlitAccent
        case .quietField:
            quietGreen
        case .prismLedger:
            prismAccent
        case .immersion:
            immersionAccent
        }
    }

    static func appChromeBackground(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).canvas
    }

    static func appSurface(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).surface
    }

    static func appInk(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).ink
    }

    static func appMuted(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).muted
    }

    static func appDivider(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).divider
    }

    static func appAccentForeground(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).accentForeground
    }

    static func appAccentSoft(for theme: PulseVisualTheme) -> Color {
        palette(for: theme).accentSoft
    }

    static func editorialDisplayFont(size: CGFloat, relativeTo style: Font.TextStyle) -> Font {
        .custom("NotoSerifSC-Regular", size: size, relativeTo: style)
    }

}

struct PulseScreenBackground: View {
    @Environment(\.pulseVisualTheme) private var visualTheme
    @Environment(\.colorScheme) private var colorScheme

    @ViewBuilder
    var body: some View {
        PulseDesign.appChromeBackground(for: visualTheme)
            .overlay {
                if visualTheme == .editorialJournal {
                    Image("PulseJournalPaper")
                        .resizable(resizingMode: .tile)
                        .blendMode(colorScheme == .dark ? .softLight : .multiply)
                        .opacity(0.42)
                        .accessibilityHidden(true)
                }
            }
            .ignoresSafeArea()
    }
}

enum PulseFieldPresentation {
    case standard
    case today
}

enum PulseAmbientMotionPolicy {
    static func allowsMotion(
        requested: Bool,
        reduceMotion: Bool,
        sceneIsActive: Bool
    ) -> Bool {
        requested && !reduceMotion && sceneIsActive
    }
}

struct PulseFieldBackground: View {
    var presentation: PulseFieldPresentation = .standard
    var allowsMotion = true
    @Environment(\.pulseVisualTheme) private var theme

    var body: some View {
        Group {
            if presentation == .today {
                switch theme {
                case .prismLedger:
                    LinearGradient(
                        colors: [PulseDesign.appAccentSoft(for: theme).opacity(0.28), .clear],
                        startPoint: .top,
                        endPoint: .center
                    )
                case .immersion:
                    // One pool of light behind the day's number.
                    RadialGradient(
                        colors: [PulseDesign.appAccentSoft(for: theme).opacity(0.9), .clear],
                        center: UnitPoint(x: 0.84, y: 0.04),
                        startRadius: 0,
                        endRadius: 460
                    )
                default:
                    EmptyView()
                }
            }
        }
        .ignoresSafeArea()
        .allowsHitTesting(false)
        .accessibilityHidden(true)
    }
}
struct PulseBrandMark: View {
    var size: CGFloat = PulseDesign.brandMarkSize
    @Environment(\.pulseVisualTheme) private var visualTheme

    var body: some View {
        Image("PulseMark")
            .resizable()
            .renderingMode(.template)
            .foregroundStyle(PulseDesign.appAccent(for: visualTheme))
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

struct PulseAppHeader: View {
    let source: PulsePrimarySection
    @Environment(\.pulseVisualTheme) private var visualTheme

    var body: some View {
        HStack(spacing: 8) {
            if visualTheme == .quietField || visualTheme == .prismLedger {
                PulseBrandMark(size: 24)
            }
            Text("today.navigation_title")
                .font(visualTheme == .editorialJournal || visualTheme == .sunlitDay
                      ? PulseDesign.editorialDisplayFont(size: 21, relativeTo: .title3).weight(.semibold)
                      : .headline.weight(.medium))
                .foregroundStyle(PulseDesign.appInk(for: visualTheme))
                .lineLimit(1)
            Spacer(minLength: 16)
            NavigationLink(value: PulseNavigationDestination.settings) {
                Image(systemName: "gearshape")
                    .font(.title3)
                    .foregroundStyle(PulseDesign.appMuted(for: visualTheme))
                    .frame(width: 44, height: 44)
                    .contentShape(Rectangle())
            }
            .accessibilityLabel("settings.navigation_title")
            .accessibilityIdentifier("settings.navigation.open.\(source.rawValue)")
        }
        .frame(maxWidth: PulseDesign.regularWidthContentMaxWidth)
        .padding(.horizontal, PulseDesign.horizontalPadding)
        .frame(maxWidth: .infinity)
    }
}

struct PulseSecondaryNavigationBackButton: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.pulseVisualTheme) private var visualTheme

    var body: some View {
        Button {
            dismiss()
        } label: {
            Label {
                Text("navigation.back")
            } icon: {
                Image(systemName: "chevron.backward")
            }
            .foregroundStyle(PulseDesign.appAccent(for: visualTheme))
        }
        .accessibilityIdentifier("navigation.back")
    }
}

private struct PulseSecondaryNavigationModifier: ViewModifier {
    let isEnabled: Bool

    func body(content: Content) -> some View {
        content
            .navigationBarBackButtonHidden(isEnabled)
            .toolbar {
                if isEnabled {
                    ToolbarItem(placement: .topBarLeading) {
                        PulseSecondaryNavigationBackButton()
                    }
                }
            }
    }
}

extension View {
    func pulseSecondaryNavigation(isEnabled: Bool = true) -> some View {
        modifier(PulseSecondaryNavigationModifier(isEnabled: isEnabled))
    }

    func pulseFormRows(for theme: PulseVisualTheme) -> some View {
        listRowBackground(PulseDesign.appSurface(for: theme))
            .listRowSeparatorTint(PulseDesign.appDivider(for: theme))
    }
}
