import SwiftUI

enum PulseDesign {
    // Every color resolves from Assets.xcassets generated by build_brand_assets.py.
    static let background = Color("PulseBackground")
    static let surface = Color("PulseSurface")
    static let navigationGlyphSurface = Color("PulseNavigationGlyphSurface")
    static let grass = Color("PulseGrass")
    static let grassForeground = Color("PulseGrassForeground")
    static let action = Color("PulseAction")
    static let actionForeground = Color("PulseActionForeground")
    static let ink = Color("PulseInk")
    static let secondary = Color("PulseSecondary")
    static let separator = Color("PulseSeparator")
    static let field = Color("PulseField")
    static let shadow = Color("PulseShadow")
    static let tint = Color("AccentColor")

    static let spacing4: CGFloat = 4
    static let spacing6: CGFloat = 6
    static let spacing8: CGFloat = 8
    static let spacing9: CGFloat = 9
    static let spacing10: CGFloat = 10
    static let spacing12: CGFloat = 12
    static let spacing13: CGFloat = 13
    static let spacing16: CGFloat = 16
    static let spacing18: CGFloat = 18
    static let spacing20: CGFloat = 20
    static let spacing24: CGFloat = 24
    static let spacing28: CGFloat = 28

    static let horizontalPadding: CGFloat = spacing20
    static let screenMaxWidth: CGFloat = 680
    static let historyMaxWidth: CGFloat = 760
    static let minimumHitTarget: CGFloat = 44

    static let topBarHeight: CGFloat = 58
    static let brandMarkSize: CGFloat = 28
    static let brandMarkCornerRadius: CGFloat = 8

    static let todayHeroMinimumHeight: CGFloat = 270
    static let dayNumberSize: CGFloat = 104
    static let weekRailWidth: CGFloat = 244
    static let weekRailDot: CGFloat = 13
    static let weekRailCurrentDot: CGFloat = 20
    static let weekRailCurrentBorder: CGFloat = 5
    static let checkInDiameter: CGFloat = 152
    static let checkInMarkInset: CGFloat = 20
    static let checkInInnerHalo: CGFloat = 18
    static let checkInOuterHalo: CGFloat = 36

    static let primaryNavigationMaxWidth: CGFloat = 440
    static let primaryNavigationHeight: CGFloat = 72
    static let primaryNavigationCornerRadius: CGFloat = 24
    static let primaryNavigationItemCornerRadius: CGFloat = 18
    static let primaryNavigationSelectedRatio: CGFloat = 1.35
    static let primaryNavigationUnselectedRatio: CGFloat = 0.75
    static let primaryNavigationGap: CGFloat = spacing6
    static let primaryNavigationPadding: CGFloat = spacing6
    static let primaryNavigationGlyph: CGFloat = 30
    static let primaryNavigationHorizontalInset: CGFloat = spacing16

    static let calendarDayVisualSize: CGFloat = 34
    static let calendarDayHitSize: CGFloat = minimumHitTarget
    static let thinLineWidth: CGFloat = 1
    static let emphasisLineWidth: CGFloat = 2

    static let navigationShadowOpacity = 0.12
    static let navigationShadowRadius: CGFloat = 30
    static let navigationShadowY: CGFloat = 10
    static let actionShadowOpacity = 0.24
    static let actionShadowRadius: CGFloat = 30
    static let actionShadowY: CGFloat = 12

    static let fieldBreathingDuration = 4.8
    static let actionFloatingDuration = 3.2
    static let savingAnimationDuration = 0.18
    static let completionAnimationDuration = 0.42
}

struct PulseScreenBackground: View {
    var body: some View {
        PulseDesign.background
            .ignoresSafeArea()
    }
}

struct PulseFieldBackground: View {
    let isActive: Bool

    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var isExpanded = false

    var body: some View {
        GeometryReader { proxy in
            ZStack {
                Ellipse()
                    .stroke(PulseDesign.field.opacity(0.45), lineWidth: PulseDesign.thinLineWidth)
                    .frame(width: proxy.size.width * 2.1, height: proxy.size.height * 1.05)

                ForEach(1...3, id: \.self) { ring in
                    Ellipse()
                        .stroke(PulseDesign.field.opacity(0.06), lineWidth: 38)
                        .frame(
                            width: max(0, proxy.size.width * 2.1 - CGFloat(ring) * 76),
                            height: max(0, proxy.size.height * 1.05 - CGFloat(ring) * 76)
                        )
                }
            }
            .position(x: proxy.size.width / 2, y: proxy.size.height * 0.275)
            .scaleEffect(isExpanded ? 1.035 : 0.98)
            .opacity(isExpanded ? 1 : 0.72)
        }
        .ignoresSafeArea()
        .allowsHitTesting(false)
        .accessibilityHidden(true)
        .onAppear(perform: updateMotion)
        .onChange(of: isActive) { _, _ in updateMotion() }
        .onChange(of: reduceMotion) { _, _ in updateMotion() }
    }

    private func updateMotion() {
        guard isActive, !reduceMotion else {
            isExpanded = false
            return
        }

        isExpanded = false
        withAnimation(
            .easeInOut(duration: PulseDesign.fieldBreathingDuration)
                .repeatForever(autoreverses: true)
        ) {
            isExpanded = true
        }
    }
}

struct PulseBrandMark: View {
    var size: CGFloat = PulseDesign.brandMarkSize

    var body: some View {
        RoundedRectangle(cornerRadius: PulseDesign.brandMarkCornerRadius, style: .continuous)
            .fill(PulseDesign.action)
            .overlay {
                Image("PulseMark")
                    .resizable()
                    .renderingMode(.template)
                    .foregroundStyle(PulseDesign.actionForeground)
            }
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

struct PulseAppHeader: View {
    let source: PulsePrimarySection

    var body: some View {
        HStack(spacing: PulseDesign.spacing9) {
            PulseBrandMark()

            Text("today.navigation_title")
                .font(.system(size: 15, weight: .medium))
                .tracking(0.6)
                .foregroundStyle(PulseDesign.ink)

            Spacer(minLength: PulseDesign.spacing16)

            NavigationLink(value: PulseNavigationDestination.settings) {
                Text("settings.navigation_title")
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundStyle(PulseDesign.ink)
                    .frame(minWidth: PulseDesign.minimumHitTarget, minHeight: PulseDesign.minimumHitTarget)
            }
            .accessibilityLabel("settings.navigation_title")
            .accessibilityIdentifier("settings.navigation.open.\(source.rawValue)")
        }
        .frame(maxWidth: PulseDesign.screenMaxWidth)
        .frame(height: PulseDesign.topBarHeight)
        .padding(.horizontal, PulseDesign.horizontalPadding)
        .frame(maxWidth: .infinity)
        .dynamicTypeSize(...DynamicTypeSize.xxxLarge)
    }
}
