import SwiftUI

enum PulseDesign {
    // Every color resolves from Assets.xcassets generated by build_brand_assets.py.
    static let background = Color("PulseBackground")
    static let surface = Color("PulseSurface")
    static let navigationGlyphSurface = Color("PulseNavigationGlyphSurface")
    static let grass = Color("PulseGrass")
    static let grassForeground = Color("PulseGrassForeground")
    static let action = Color("PulseAction")
    static let actionForeground = Color("PulseActionForeground")
    static let ink = Color("PulseInk")
    static let secondary = Color("PulseSecondary")
    static let separator = Color("PulseSeparator")
    static let field = Color("PulseField")
    static let shadow = Color("PulseShadow")
    static let tint = Color("AccentColor")

    static let spacing4: CGFloat = 4
    static let spacing8: CGFloat = 8
    static let spacing12: CGFloat = 12
    static let spacing16: CGFloat = 16
    static let spacing20: CGFloat = 20
    static let spacing24: CGFloat = 24
    static let spacing32: CGFloat = 32

    static let horizontalPadding: CGFloat = spacing20
    static let screenMaxWidth: CGFloat = 680
    static let historyMaxWidth: CGFloat = 760
    static let minimumHitTarget: CGFloat = 44

    static let topBarHeight: CGFloat = 58
    static let brandMarkSize: CGFloat = 28
    static let brandMarkCornerRadius: CGFloat = 8

    static let todayHeroMinimumHeight: CGFloat = 270
    static let dayNumberBaseSize: CGFloat = 104
    static let checkInHeroOverlap: CGFloat = -42
    static let accessibilityActionMinimumHeight: CGFloat = 72
    static let weekRailWidth: CGFloat = 244
    static let weekRailDot: CGFloat = 13
    static let weekRailCurrentDot: CGFloat = 20
    static let weekRailCurrentBorder: CGFloat = 5
    static let checkInDiameter: CGFloat = 152
    static let checkInMarkInset: CGFloat = 20
    static let checkInInnerHalo: CGFloat = 18
    static let checkInOuterHalo: CGFloat = 36

    static let primaryNavigationMaxWidth: CGFloat = 440
    static let primaryNavigationHeight: CGFloat = 72
    static let primaryNavigationCornerRadius: CGFloat = 24
    static let primaryNavigationItemCornerRadius: CGFloat = 18
    static let primaryNavigationSelectedRatio: CGFloat = 1.35
    static let primaryNavigationUnselectedRatio: CGFloat = 0.75
    static let primaryNavigationGap: CGFloat = spacing8
    static let primaryNavigationPadding: CGFloat = spacing8
    static let primaryNavigationGlyph: CGFloat = 30
    static let primaryNavigationHorizontalInset: CGFloat = spacing16

    static let calendarDayVisualSize: CGFloat = 34
    static let calendarDayHitSize: CGFloat = minimumHitTarget
    static let recordDetailBrandMarkSize: CGFloat = 64
    static let thinLineWidth: CGFloat = 1
    static let emphasisLineWidth: CGFloat = 2
    static let fieldBandWidth: CGFloat = 38
    static let fieldRingCount = 3
    static let fieldWidthRatio = 2.1
    static let fieldHeightRatio = 1.05
    static let fieldRingInset: CGFloat = 76
    static let fieldVerticalPositionRatio = 0.275
    static let fieldExpandedScale = 1.035
    static let fieldCollapsedScale = 0.98

    static let navigationShadowOpacity = 0.12
    static let navigationShadowRadius: CGFloat = 30
    static let navigationShadowY: CGFloat = 10
    static let navigationSurfaceOpacity = 0.9
    static let navigationSubtitleOpacity = 0.76
    static let actionShadowOpacity = 0.24
    static let actionShadowRadius: CGFloat = 30
    static let actionShadowY: CGFloat = 12
    static let actionBorderOpacity = 0.55
    static let actionRingOpacity = 0.62
    static let outerHaloOpacity = 0.07
    static let innerHaloOpacity = 0.12
    static let fieldOutlineOpacity = 0.45
    static let fieldBandOpacity = 0.06
    static let fieldCollapsedOpacity = 0.72
    static let deemphasizedCalendarOpacity = 0.62

    static let fieldBreathingDuration = 4.8
    static let savingAnimationDuration = 0.18
    static let completionAnimationDuration = 0.42
}

struct PulseScreenBackground: View {
    var body: some View {
        PulseDesign.background
            .ignoresSafeArea()
    }
}

struct PulseFieldBackground: View {
    let isActive: Bool

    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var isExpanded = false

    var body: some View {
        GeometryReader { proxy in
            ZStack {
                Ellipse()
                    .stroke(
                        PulseDesign.field.opacity(PulseDesign.fieldOutlineOpacity),
                        lineWidth: PulseDesign.thinLineWidth
                    )
                    .frame(
                        width: proxy.size.width * PulseDesign.fieldWidthRatio,
                        height: proxy.size.height * PulseDesign.fieldHeightRatio
                    )

                ForEach(1...PulseDesign.fieldRingCount, id: \.self) { ring in
                    Ellipse()
                        .stroke(
                            PulseDesign.field.opacity(PulseDesign.fieldBandOpacity),
                            lineWidth: PulseDesign.fieldBandWidth
                        )
                        .frame(
                            width: max(
                                0,
                                proxy.size.width * PulseDesign.fieldWidthRatio
                                    - CGFloat(ring) * PulseDesign.fieldRingInset
                            ),
                            height: max(
                                0,
                                proxy.size.height * PulseDesign.fieldHeightRatio
                                    - CGFloat(ring) * PulseDesign.fieldRingInset
                            )
                        )
                }
            }
            .position(
                x: proxy.size.width / 2,
                y: proxy.size.height * PulseDesign.fieldVerticalPositionRatio
            )
            .scaleEffect(
                isExpanded ? PulseDesign.fieldExpandedScale : PulseDesign.fieldCollapsedScale
            )
            .opacity(isExpanded ? 1 : PulseDesign.fieldCollapsedOpacity)
        }
        .ignoresSafeArea()
        .allowsHitTesting(false)
        .accessibilityHidden(true)
        .onAppear(perform: updateMotion)
        .onChange(of: isActive) { _, _ in updateMotion() }
        .onChange(of: reduceMotion) { _, _ in updateMotion() }
    }

    private func updateMotion() {
        guard isActive, !reduceMotion else {
            isExpanded = false
            return
        }

        isExpanded = false
        withAnimation(
            .easeInOut(duration: PulseDesign.fieldBreathingDuration)
                .repeatForever(autoreverses: true)
        ) {
            isExpanded = true
        }
    }
}

struct PulseBrandMark: View {
    var size: CGFloat = PulseDesign.brandMarkSize

    var body: some View {
        RoundedRectangle(cornerRadius: PulseDesign.brandMarkCornerRadius, style: .continuous)
            .fill(PulseDesign.action)
            .overlay {
                Image("PulseMark")
                    .resizable()
                    .renderingMode(.template)
                    .foregroundStyle(PulseDesign.actionForeground)
            }
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

struct PulseAppHeader: View {
    let source: PulsePrimarySection

    var body: some View {
        HStack(spacing: PulseDesign.spacing8) {
            PulseBrandMark()

            Text("today.navigation_title")
                .font(.subheadline.weight(.medium))
                .foregroundStyle(PulseDesign.ink)

            Spacer(minLength: PulseDesign.spacing16)

            NavigationLink(value: PulseNavigationDestination.settings) {
                Text("settings.navigation_title")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(PulseDesign.ink)
                    .frame(minWidth: PulseDesign.minimumHitTarget, minHeight: PulseDesign.minimumHitTarget)
            }
            .accessibilityLabel("settings.navigation_title")
            .accessibilityIdentifier("settings.navigation.open.\(source.rawValue)")
        }
        .frame(maxWidth: PulseDesign.screenMaxWidth)
        .frame(minHeight: PulseDesign.topBarHeight)
        .padding(.horizontal, PulseDesign.horizontalPadding)
        .frame(maxWidth: .infinity)
    }
}
